CLASS zcl_lab_51_wz_friend_426 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  global FRIENDS zcl_lab_50_work_zone426.

  PUBLIC SECTION.

    METHODS GET_HELPER.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_51_wz_friend_426 IMPLEMENTATION.
  METHOD get_helper.

  ENDMETHOD.

ENDCLASS.
