CLASS zcl_lab_12_linux_426 DEFINITION INHERITING FROM zcl_lab_11_system_426
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.


  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_12_LINUX_426 IMPLEMENTATION.
ENDCLASS.
