CLASS zcl_33_record__426 DEFINITION INHERITING FROM zcl_32_contract_cntr__426
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_33_record__426 IMPLEMENTATION.
ENDCLASS.
