CLASS zcl_lab_23_company_426 DEFINITION
  PUBLIC
*  FINAL
  CREATE PUBLIC
  GLOBAL FRIENDS zcl_lab_24_partner_426.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
    data CAPITAL type string.
ENDCLASS.

CLASS zcl_lab_23_company_426 IMPLEMENTATION.
ENDCLASS.
