CLASS zcl_06_storage_426 DEFINITION INHERITING FROM zcl_05_plant_426
  PUBLIC

  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_06_STORAGE_426 IMPLEMENTATION.
ENDCLASS.
