CLASS zcl_23_passenger_plane_426 DEFINITION INHERITING FROM zcl_21_airplane_426
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: airplane_type REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_23_PASSENGER_PLANE_426 IMPLEMENTATION.


  METHOD airplane_type.
    rv_airplane = 'Panssanger Plane'.
  ENDMETHOD.
ENDCLASS.
