CLASS zcl_22_cargoplane_426 DEFINITION  INHERITING FROM zcl_21_airplane_426
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: airplane_type REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_22_CARGOPLANE_426 IMPLEMENTATION.


  METHOD airplane_type.
    rv_airplane = 'Cargo Plane'.
  ENDMETHOD.
ENDCLASS.
