CLASS zcl_31_indicador_426 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    data vat_ind TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_31_indicador_426 IMPLEMENTATION.
ENDCLASS.
