CLASS zcl_10_eu_citizen_426 DEFINITION INHERITING FROM zcl_09_citizen_426
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_10_EU_CITIZEN_426 IMPLEMENTATION.
ENDCLASS.
