CLASS zcl_21_airplane_426 DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS airplane_type ABSTRACT RETURNING VALUE(rv_airplane) type string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_21_AIRPLANE_426 IMPLEMENTATION.
ENDCLASS.
