CLASS zcl_lab_42_screen DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  data pos type i.

  EVENTS TOUCH_SCREEN EXPORTING value(ev_pos) type i.

  METHODS ELEMENT_SELECTED.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_42_screen IMPLEMENTATION.
  METHOD element_selected.
    RAISE EVENT TOUCH_SCREEN EXPORTING ev_pos = me->pos.
  ENDMETHOD.

ENDCLASS.
