CLASS zcl_lab_31_org_france_426 DEFINITION INHERITING FROM zcl_lab_29_organization_426
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS GET_LOCATION REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_31_org_france_426 IMPLEMENTATION.
  METHOD get_location.
    rv_location = 'France'.
  ENDMETHOD.

ENDCLASS.
