CLASS zcl_20_honda_crv_426 DEFINITION INHERITING FROM zcl_19_honda_426
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
    METHODS: set_model REDEFINITION,
             set_max_speed REDEFINITION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_20_HONDA_CRV_426 IMPLEMENTATION.


  METHOD set_max_speed.

  ENDMETHOD.


  METHOD set_model.

  ENDMETHOD.
ENDCLASS.
