CLASS zcl_lab_11_system_426 DEFINITION
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    data ARCHITECTURE TYPE string VALUE '64BITS'.

    METHODS GET_ARCHITECTURE RETURNING VALUE(rv_arch) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_11_system_426 IMPLEMENTATION.
  METHOD get_architecture.

  ENDMETHOD.

ENDCLASS.
