CLASS zcl_lab_37_screen_426 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    data screen_type TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_37_screen_426 IMPLEMENTATION.
ENDCLASS.
