CLASS zcl_lab_38_prod_price_426 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    data price TYPE i.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_38_prod_price_426 IMPLEMENTATION.
ENDCLASS.
