CLASS zcl_lab_27_factory DEFINITION ABSTRACT
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS MERCHANDISE_OUTPUT RETURNING VALUE(RV_MERCHENDISE) type string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_27_FACTORY IMPLEMENTATION.


  METHOD merchandise_output.
    rv_merchendise = 'MERCHANDISE_OUTPUT'.
  ENDMETHOD.
ENDCLASS.
