CLASS zcl_29_keyborad_426 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    data keyboard_type TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_29_keyborad_426 IMPLEMENTATION.
ENDCLASS.
