CLASS zcl_19_honda_426 DEFINITION ABSTRACT INHERITING FROM zcl_18_moto_426
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
    METHODS set_model ABSTRACT EXPORTING model type string.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_19_HONDA_426 IMPLEMENTATION.
ENDCLASS.
