CLASS zcl_lab_15_flight_price_426 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    data MT_FLIGHTS TYPE STANDARD TABLE OF /DMO/FLIGHT.

    METHODS ADD_PRICE IMPORTING add_price TYPE /DMO/FLIGHT.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_15_flight_price_426 IMPLEMENTATION.
  METHOD add_price.
    select from /DMO/FLIGHT
        FIELDS *
        into table @mt_flights.




  ENDMETHOD.

ENDCLASS.
